### ISSUE TITLE
Remove Hybrid quickstart Runtime Image Patch with the Next Release

### ISSUE THREAD

**Issue by danistrebel** [apigee/devrel#430]
The Quickstart applies a hotfix as per https://cloud.google.com/apigee/docs/hybrid/v1.6/hotfix-install.

The runtime image patch introduced in #429 includes a hotfix image tag that should be removed from the quickstart once the next release includes it.

```yaml
runtime:
  image:
    url: "gcr.io/apigee-release/hybrid/apigee-runtime"
    tag: "1.6.2-hotfix.1"  # TODO remove hotfix image tag with 1.6.3
```
